LabRedesCefetRJ/WeGIA

- BD/wegia001.sql
- classes/Aviso.php
- classes/AvisoNotificacao.php
- controle/AvisoControle.php
- controle/AvisoNotificacaoControle.php
- controle/SaudeControle.php
- dao/AtendidoDAO.php
- dao/AvisoDAO.php
- dao/AvisoNotificacaoDAO.php
- dao/DescricaoDAO.php
- dao/EnderecoDAO.php
- dao/FuncionarioDAO.php
- html/adicionar_almoxarife.php
- html/atendido/Profile_Atendido.php
- html/atendido/atendido_parentesco_adicionar.php
- html/atendido/atendido_parentesco_listar.php
- html/atendido/cadastro_atendido_pessoa_existente.php
- html/atendido/documento_upload.php
- html/atendido/familiar_parentesco_adicionar.php
- html/atendido/profile_familiar.php
- html/funcionario/dependente_parentesco_adicionar.php
- html/header.php
- html/relatorio.php
- html/saude/aplicar_medicamento.php
- html/saude/emergencia_visualizar.php
- html/saude/historico_paciente.php
- html/saude/intercorrencia_visualizar.php
- html/saude/profile_paciente.php
Criação de duas novas tabelas no banco de dados, aviso e aviso_notificacao.
Necessária a criação de um usuário que seja um funcionário com cargo de "Enfermeiro(a)" ou "Téc. Enfermagem" para testar a implementação da funcionalidade de notificação no servidor em produção, ele deve ter acesso ao módulo de saúde e poder realizar as ações de ler, gravar e executar.
> Alterações realizadas entre 29/02 e 13/03

- html/contribuicao/php/getaway_pagamento.php
- html/contribuicao/php/meio_pagamento.php
- html/contribuicao/php/regras_pagamento.php
- html/home.php
- html/menu.html
- html/menu.php
> Novo módulo de contribuição

- dao/pet/exibir_cor.php
- dao/pet/exibir_raca.php
- html/listar_entrada.php
- html/pet/cadastro_pet.php
- html/pet/informacao_medicamento.php
- html/pet/informacao_pet.php
- html/pet/informacao_saude_pet.php
9 issues corrigidas [#123 - #258 - #259 - #260 - #449 - #451 - #576 - #577 - #578];
> Pet240904 

- BD/wegia001.sql
- html/contribuicao/configuracao/assets/js/configuracoesGerais.js
- html/contribuicao/configuracao/assets/js/gatewayPagamento.js
- html/contribuicao/configuracao/assets/js/meioPagamento.js
- html/contribuicao/configuracao/assets/js/regraPagamento.js
- html/contribuicao/configuracao/src/controller/GatewayPagamentoController.php
- html/contribuicao/configuracao/src/controller/MeioPagamentoController.php
- html/contribuicao/configuracao/src/controller/RegraPagamentoController.php
- html/contribuicao/configuracao/src/dao/GatewayPagamentoDAO.php
- html/contribuicao/configuracao/src/dao/MeioPagamentoDAO.php
- html/contribuicao/configuracao/src/dao/RegraPagamentoDAO.php
- html/contribuicao/configuracao/src/model/GatewayPagamento.php
- html/contribuicao/configuracao/src/model/MeioPagamento.php
- html/contribuicao/configuracao/src/model/RegraPagamento.php
- html/saude/aplicar_medicamento.php
**Observação:** Campo `status` adicionado às tabelas `contribuicao_gatewayPagamento`, `contribuicao_meioPagamento` e `contribuicao_conjuntoRegras`
> Solicitação de merge das alterações realizadas em contribuicao240916 para pre-master-2409

- html/saude/intercorrencia_visualizar.php
- html/saude/listar_historico_pacientes.php
> Saude240918

- html/adicionar_almoxarifado.php
- html/adicionar_categoria.php
- html/adicionar_tipoEntrada.php
- html/adicionar_tipoSaida.php
- html/adicionar_unidade.php
- html/cadastro_doador.php
- html/cadastro_entrada.php
- html/cadastro_saida.php
- html/listar_entrada.php
- html/listar_saida.php
- html/listar_tipoSaida.php
- html/relatorio_geracao.php
Issues #701 e #103 resolvidas.
> Alterações MatPat 25/09/2024

- html/socio/js/cadastro_socio.js
Ajustes no formulário de auto cadastro do sócio.
> Fix [Issue #753]

- classes/Atendido_ocorrenciaDoc.php
- html/funcionario/dependente_editarEndereco.php
- html/funcionario/dependente_parentesco_adicionar.php
- html/funcionario/documento_download.php
Correção das issues de vulnerabilidade de segurança
> Pessoa 241023

- html/pet/cadastro_ficha_medica_pet.php
- html/pet/cadastro_pet.php
- html/pet/profile_pet.php
issue[#723] & issue[#595 - #690]
> Pet 241023

- html/pet/cadastro_pet.php
- html/pet/profile_pet.php
> Pet 241031

- BD/wegia001.sql
- classes/pet/padrinho/Padrinho.php
- controle/PadrinhoControle.php
- controle/pet/padrinho/PadrinhoControle.php
- dao/pet/AdocaoPet.php
- dao/pet/padrinho/PadrinhoDAO.php
- html/home.php
- html/menu.html
- html/menu.php
- html/personalizacao_display.php
- html/pet/padrinho/cadastro_padrinho.php
- html/pet/padrinho/cadastro_padrinho_pessoa_existente.php
- html/pet/padrinho/informacao_padrinho.php
- html/pet/padrinho/pre_cadastro_padrinho.php
- html/pet/padrinho/profile_padrinho.php
> Cadastro de padrinhos

- BD/wegia002.sql
- controle/AtendidoControle.php
- dao/AtendidoDAO.php
- html/atendido/Profile_Atendido.php
- html/geral/deletar_documento.php
- html/geral/deletar_permissao.php
- html/geral/salvar_cargo.php
- html/home.php
- html/saude/historico_paciente.php
- html/saude/profile_paciente.php
- html/socio/sistema/get_codigobarras_cobranca.php
- html/socio/sistema/get_detalhes_cobranca.php
- html/socio/sistema/get_detalhes_socio.php
- html/socio/sistema/salvar_tag.php
INSERT INTO `atendido_status` (`idatendido_status`, `status`) VALUES (2, 'Inativo');
> Alterações semanais Equipe laje250121

- BD/wegia002.sql
- html/adicionar_almoxarife.php
- html/atendido/familiar_docfamiliar.php
- html/funcionario/dependente_docdependente.php
- html/funcionario/documento_excluir.php
- html/funcionario/informacao_adicional.php
- html/geral/deletar_cargo.php
- html/remover_produto.php
- html/restaurar_produto_desocultar.php
- html/saude/adicionar_alergia.php
- html/saude/alergia_excluir.php
- html/saude/alergia_upload.php
- html/saude/historico_paciente.php
- html/saude/profile_paciente.php
INSERT INTO `recurso` (`id_recurso`, `descricao`) VALUES (53, 'Alergia');
> Alterações semanais Equipe laje 250203

- controle/pet/AdocaoControle.php
- controle/pet/ControleObterAdotante.php
- dao/pet/AdocaoPet.php
- dao/pet/PetDAO.php
- dao/pet/SaudePetDAO.php
- dao/pet/adicionar_cor.php
- dao/pet/adicionar_especie.php
- dao/pet/adicionar_raca.php
- dao/pet/exibir_cor.php
- dao/pet/exibir_especie.php
- html/menu.php
- html/pet/adotantes/cadastro_adotante.php
- html/pet/adotantes/informacao_adotantes.php
- html/pet/adotantes/pre_cadastro_adotante.php
- html/pet/cadastrar_medicamento.php
- html/pet/cadastro_ficha_medica_pet.php
- html/pet/cadastro_pet.php
- html/pet/informacao_medicamento.php
- html/pet/informacao_pet.php
- html/pet/informacao_saude_pet.php
- html/pet/profile_pet.php
> Revert "Estagiarios miados e latidos250326"

- controle/getProdutosPorAlmox.php
- html/matPat/relatorio_geracao.php
Finalização do tratamento das vulnerabilidades [GHSA-pmf9-2rc3-vvxx]  e [GHSA-43xw-c4g6-jgff]
> Resolvendo [GHSA-pmf9-2rc3-vvxx]  e [GHSA-43xw-c4g6-jgff]

- controle/pet/MedicamentoControle.php
- html/configuracao/atualizacao.php
- html/configuracao/debug_info.php
- html/pet/cadastrar_medicamento.php
Commits de mitigação de Command Injection e inclusão de arquivo em `html/configuracao/debug_info.php`
> Consertos de segurança 16/06/2025

- html/contribuicao/dao/SocioDAO.php
- html/contribuicao/public/js/util.js
- html/contribuicao/view/components/contribuicao_contato.php
- html/geral/cargos.php
- html/geral/documentos_funcionario.php
Implementação de melhoria da usabilidade para usuários do mobile.
> Alteração do tipo de campo date para text [Issue #1048]

- controle/memorando/MemorandoControle.php
- dao/memorando/MemorandoDAO.php
- html/funcionario/profile_funcionario.php
Pull request para envio do restante das correções de segurança da semana 22-28/06/2025
> Equipe laje 250616

- controle/control.php
- controle/pet/AdocaoControle.php
- controle/pet/ControleObterAdotante.php
- controle/pet/PetControle.php
- dao/pet/AdocaoPet.php
- dao/pet/PetDAO.php
- dao/pet/SaudePetDAO.php
- dao/pet/adicionar_cor.php
- dao/pet/adicionar_especie.php
- dao/pet/adicionar_raca.php
- dao/pet/exibir_cor.php
- dao/pet/exibir_especie.php
- html/home.php
- html/menu.php
- html/pet/adotantes/cadastro_adotante.php
- html/pet/adotantes/informacao_adotantes.php
- html/pet/adotantes/pre_cadastro_adotante.php
- html/pet/cadastrar_medicamento.php
- html/pet/cadastro_ficha_medica_pet.php
- html/pet/cadastro_pet.php
- html/pet/informacao_medicamento.php
- html/pet/informacao_pet.php
- html/pet/informacao_saude_pet.php
- html/pet/profile_pet.php
Merge das alterações do módulo pet
> Pre master 250703

- controle/pet/PetControle.php
- controle/pet/controleSaudePet.php
- dao/pet/PetDAO.php
- dao/pet/SaudePetDAO.php
- html/menu.php
- html/pet/cadastro_ficha_medica_pet.php
- html/pet/profile_pet.php
> Joaquim 250821
